[package]
name = "teardown_tree"
version = "0.4.2"
authors = ["Kirill Khazan <kirillkh@gmail.com>"]
description = "A binary search tree that supports fast clone and delete-range operations"
readme = "README.rst"
license-file = "LICENSE-MIT"
homepage = "https://github.com/kirillkh/rs_teardown_tree"
repository = "https://github.com/kirillkh/rs_teardown_tree.git"
keywords = ["BST", "tree", "teardown"]

[lib]
name = "teardown_tree"
path = "src/lib.rs"

[[bin]]
name = "benchmarks"
path = "src/bin/benchmarks.rs"

[dependencies]
rand = "0.3.14"
#wio = "0.1.2"


[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
codegen-units = 1


[features]
unstable = []
